### PR TITLE
Added support for sharing a selection via the native share sheet.

### PR DESCRIPTION
**Pull request by shaps80**
This is a draft to get early eyes on the other changes I've made. I will push the final updates tomorrow.

- Updated all schemes and targets to the latest Xcode 11 Beta 3 settings
- Fixed some warnings
- Fixed some potential issues where we may have ended up dereferencing a null pointer
- Refactored the UIKeyCommand setups to use the non-deprecated APIs.

Regarding the share feature, I still need to do the following:

- If the selection contains a URL, included that in the activity
- Test on iPhone

### CODE REVIEW

**Comment by yury** [comment]
Hi @shaps80, it looks like this is draft and not ready for review. But I want to note that, it is better not to include changes about team and iCloud ids.

I can bring them back, but it would be super cool if you just don't include that changes.

**Comment by shaps80** [comment]
> Hi @shaps80, it looks like this is draft and not ready for review. But I want to note that, it is better not to include changes about team and iCloud ids.
> 
> I can bring them back, but it would be super cool if you just don't include that changes.

Apologies I did mean to leave those out. My bad. I wanted to get a draft out last night cause there were warnings and other areas I just tried to help clean up. So I knew it wasn't ready yet.

But for sure I will ensure I pull those out every time. Sorry again thanks for the reminder :)

**Comment by yury** [comment]
Another note: Do not fix SpaceController or TermController - I rewrote them in swift. Hope to make PR tomorrow.

**Comment by shaps80** [comment]
I’ll pull out those changes :)

**Comment by yury** [comment]
@shaps80 thank you very much for PR. We rewrote a lot of parts of the app.
So I just grab share part. See [commit](https://github.com/blinksh/blink/commit/8d416a348c3e25cc99addc6de51f60f011797a94)

Again. Thank you!

**Pull request closed without merging**
