### PR TITLE
Implements CapsLock and Backquote mapping

### PR DESCRIPTION
**Pull request by BillWSY**
I map `CapsLock to Ctrl` and `` ` to Esc`` on my Mac keyboard. Thought it would be useful to implement it in Blink as well.

### CODE REVIEW

**Comment by goerz** [comment]
How do you type a backquote?

**Comment by BillWSY** [comment]
Ctrl/Option + backquote will produce a backquote.

**Comment by yury** [comment]
Hi @BillWSY,

Looks good to me but still needs some time to test on devices. Will merge after 12.2 release. (Hope it will be today :)

Thank you.

**Comment by BillWSY** [comment]
Thank you!

**Comment by yury** [comment]
@BillWSY 
Merged! Thank you.

**Comment by vorband** [comment]
I am also using the German layout, so support for using the actual key on the upper left instead of the character ~ as ESC would be awesome.

**Pull request merged**
