### PR TITLE
Use linenoise fork with utf8 support [closes #49]

### LINKED ISSUE #49: crash on backspace after unicode character
The app crashes when entering any non-ascii unicode character (e.g. an umlaut, or an emoji) at the `blink>` prompt, followed by a backspace/delete.

### PR DESCRIPTION
**Pull request by yury**
Use  @yhirose [linenoise fork](https://github.com/yhirose/linenoise/tree/utf8-support) with utf8 support

### CODE REVIEW

**Comment by carloscabanero** [comment]
Thanks Yuri, testing now :+1:

**Comment by carloscabanero** [comment]
Great job! There are still a couple things to change, like redefining STDOUT_FILENO, return values for a few keys, etc... But so far so good :) I will make sure we can have this in the next version tomorrow.

**Comment by carloscabanero** [comment]
It fixes linenoise doing crazy things or crashing, but I cannot get the special utf characters to print. Do you get those?

**Comment by yury** [comment]
utf special characters? I tested in russian.

img_0139

Yep, emojis doesn't work well.

**Comment by carloscabanero** [comment]
My fault, working now!!

**Pull request closed without merging**
