### PR TITLE
Adding shell utilities to Blink

### PR DESCRIPTION
**Pull request by holzschu**
I suggest an extension to Blink, giving basic shell commands inside the shell (cp, rm, mv...)
This might help user in managing their private keys, or storing files locally. 

This is based on GNU coreutils, edited so they compile for iOS and work as functions instead of commands. For each command (e.g. "ls") I rename its main function (e.g. "ls_main"), and call this function from inside MCPSession.m

The full list of commands available: 
cd ln ls cp  mv rm mkdir rmdir touch pwd
setenv env printenv
id groups realpath uname 

For more functionalities, I suggest also compiling VimIOS and creating an App Group, so the two apps can share files. Once this is done, you can edit files in VimIOS and copy/delete them in Blink. 

Only a small set of the GNU coreutils are available: some of them don't make sense in a sandboxed environment (kill, nohup, nice, chown), others don't work in a function because of local variables (df), still others send their output to STDOUT_FILENO instead of stdout, which was too complicated to change (cat).

### CODE REVIEW

**Comment by carloscabanero** [comment]
Just a quick note before reviewing or talking in more detail. The GNU Coreutils are under the GPL3, and unfortunately it is incompatible with Blink - Mosh iOS clause. But maybe we can build the BSD versions?

**Comment by holzschu** [comment]
Hi, 

> On 13 Jun 2017, at 19:57, carloscabanero <notifications@github.com> wrote:
> Just a quick note before reviewing or talking in more detail. The GNU Coreutils are under the GPL3, and unfortunately it is incompatible with Blink - Mosh iOS clause. But maybe we can build the BSD versions?
> 
> 

Damn! I knew there would be some licensing issues, but not so fast. 

I'll look at the BSD version of the tools. On the plus side, the commands are easier to tinker with. 

Best, 
Nicolas Holzschuch

**Comment by holzschu** [comment]
Hi, 

> On 13 Jun 2017, at 19:57, carloscabanero <notifications@github.com <mailto:notifications@github.com>> wrote:
> Just a quick note before reviewing or talking in more detail. The GNU Coreutils are under the GPL3, and unfortunately it is incompatible with Blink - Mosh iOS clause. But maybe we can build the BSD versions?
> 
> 
Quick question: is the *Apple* license OK? 

By far the easiest utilities to port are the ones from Apple's own Open Source effort: 
https://opensource.apple.com <https://opensource.apple.com/>

Reading the source code, it seems to be following the BSD licence: 
/*
 * Copyright (c) 1989, 1993, 1994
 *	The Regents of the University of California.  All rights reserved.
 *
 * This code is derived from software contributed to Berkeley by
 * Michael Fischbein.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *	This product includes software developed by the University of
 *	California, Berkeley and its contributors.
 * 4. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

Best regards, 
Nicolas Holzschuch

**Comment by carloscabanero** [comment]
This is a tricky one, that is the original 4-clause BSD, which is incompatible with GPLv3. The problem is clause 3. But FreeBSD relicensed all their code to a compatible 3-clause one, including the Core Utils we care about (reason why in their license files they skip the 3). The code is technically the same, do you think we can use that one?

**Comment by carloscabanero** [comment]
Thanks! I will prepare a new version for the Raw branch with this included. Don’t know what people will do with it, but interesting to figure out! :)

**Comment by goerz** [comment]
What would make this massively useful is to have `vim` included. I was trying to compile this myself, but I don't think I can, without a paid dev account (because of iCloud etc)

**Comment by holzschu** [comment]
I'll look into it, but it's a long shot. 
It could work, but I don't think it's going to be easy. Vim needs a terminal that implements libcurses, which is a bit too much for Blink. The alternative would be to persuade the Vim developer to have a joint app group with Blink.

**Comment by goerz** [comment]
Having VimIOS separate but with a shared folder sounds like it could work. Do you know if there's a reason that VimIOS is not on the app store? Licensing issue? I did eventually manage to compile it myself, but since I don't have a paid developer account, I had to muck with it to take out iCloud support, and I think it also expires after 7 days (at least it crashes now when I start it). I'm also missing Blink's nice theming and the all-important Caps-Lock-to-Esc mapping. It seems a little like the VimIOS project is semi-abandoned. Would you or Carlos potentialy be able to release VimIOS on the app store, with the necessary modifications to make it work in conjunction with Blink? I'd be more than happy to pay for it!

**Comment by ishcabittle** [comment]
Would it be possible to add other shell utilities, ones that focus more on network troubleshooting such as nmap, telnet, ping, etc?

**Comment by holzschu** [comment]
- I'm going to work on ping and traceroute and the other small network commands from Apple Open Source (https://opensource.apple.com/source/network_cmds/network_cmds-543/). 
- nmap is a really big package, so it makes less sense. Isn't Scany (https://itunes.apple.com/us/app/scany-network-scanner/id328077901) already doing the same job for iOS? 
- do you really need telnet if you already have ssh, which is basically telnet with ssh security?

**Comment by ishcabittle** [comment]
Telnet is useful for checking if ports are open (i.e. telnet hostname 8080 to check if Tomcat is up) and for the occasional piece of equipment that only supports telnet (I have several old tape autoloaders that only do telnet). 

Nmap is kind of pie in the sky, thank you for point me to Scany.

**Comment by holzschu** [comment]
I've just done "ping". If you want to test it, it's in my branch: https://github.com/holzschu/blink
You can compile, sideload it and test. 
The big difference is that I can't catch interruptions (hitting ctrl-C doesn't work). Which is a big issue with ping, since it keeps sending packages and waits for the user to stop it. So I made "ping -c 9" the default behaviour.

**Comment by holzschu** [comment]
Okay, so ping is done, traceroute is impossible because it requires opening a socket with root privilege (not feasible with a sandboxed app), and I couldn't compile telnet (it requires a header file, mp.h, which I couldn't find anywhere). 

The good news is that python has a telnetlib module, so you can telnet into a machine with that. Easiest choice would be to use Pythonista. There is also my port of python for blink, https://github.com/holzschu/python_ios

**Comment by yury** [comment]
@holzschu tried to merge this branch.

Can't open Xcode... it crashes.

This is [log](https://gist.github.com/yury/f5a905efb99c3d6f4ac4e69d1438a4ee) I get. Any help on that?

**Comment by holzschu** [comment]
Hi @yury, 
I observed the same issue with the latest version of Blink, yesterday. Everything was fine until then.

In your log, "makeDocumentForURL" relates to Xcode or Blink?

**Comment by holzschu** [comment]
Update: Copying a fresh project.pbxproj from the main branch allows me to move past the Xcode crash. Of course, all the changes I made to the project have disappeared.

**Comment by yury** [comment]
@holzschu thank you. Will try to apply changes manually.

**Comment by holzschu** [comment]
I'm also doing it. Give me a few minutes to push something that is merged.

**Comment by yury** [comment]
Cool.

**Comment by holzschu** [comment]
I am now stuck on compilation, "too many arguments in function call (mosh_main), expected 7, got 11:
```
/Users/holzschu/src/Xcode_iPad/blink/Sessions/MoshSession.m:227:13: error: too many arguments to function call, expected 7, have 11
            [self.sessionParameters.key UTF8String],
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/holzschu/src/Xcode_iPad/blink/Sessions/MoshSession.m:37:
/Users/holzschu/src/Xcode_iPad/blink/Frameworks/libmoshios.framework/Headers/moshiosbridge.h:10:1: note: 'mosh_main' declared here
int mosh_main(FILE *f_in, FILE *f_out, struct winsize *window_size,
^
1 error generated.
```

I also can't compile the main branch (brand new clone) because: 
```
blink/Frameworks/PasscodeLock/PasscodeLock/Info.plist:0: error: reading data: The file “Info.plist” couldn’t be opened because there is no such file.
```

**Comment by yury** [comment]
I emailed you updated libmosh

**Comment by holzschu** [comment]
It compiles now, but crashes on launch with:
```
2018-02-16 11:49:39.309901+0100 Blink[4704:1258863] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'Main' in bundle NSBundle </var/containers/Bundle/Application/FB20EF45-FCE3-48CB-9334-65500A295777/Blink.app> (loaded)'
```
(there is quite a lot of TODOs in MCPSession.m, but it compiles)

**Comment by yury** [comment]
Ok, I can pickup from here. Thanks!

**Comment by holzschu** [comment]
I'll let you work. There is still "curl" to merge into the project. Let me know when I can try to do it.

**Comment by yury** [comment]
Ok, got it working at https://github.com/yury/blink/tree/utils

**Comment by holzschu** [comment]
Finished the merge by adding back the curl_ios_static project (so scp, sftp and curl work by using Blink keys). I assumes the ios_system source tree is next to the blink source tree.

Also added libnetwork_ios.dylib in the embedded libraries (see https://github.com/holzschu/network_ios )

**Comment by yury** [comment]
@holzschu I got few questions.

- How can I run tools on iOS simulator? I need to rebuild all tools with 386 arch?
- How can I trap ctrl-c to call `ios_kill`? For instance, if I run `ping` command and press ctrl-c, ping finishes and then MCPSession gets ctrl-c and exits.
- Something with keys. In this branch all my hosts starts to ask password from me instead of using my key.
- awk command doesn't work - it failed function from libtext.dylib.

thanks for any help in advance.

**Comment by holzschu** [comment]
Hi @yury, to answer your questions: 
- yes, to run tools on the simulator, you need to rebuild all tools with 386 arch. I use `xcodebuild -project ios_system.xcodeproj -alltargets -sdk iphonesimulator -configuration Debug -quiet` to do all compilations in a single run. 
- I'm not sure about how to trap ctrl-c. It has to be done outside of ios-system, when the key is pressed, before it is sent to stdin. To avoid issues, `ping` stops after 9 tries (the default behaviour is `ping -n 9`)
- I'm not sure about keys. `ssh` calls `[self _runSSHWithArgs:cmdline]` so it goes to `SSHSession`, and I don't think I changed anything in this one, but it may be different from the current version. Is the behaviour you describe with `ssh`, or is it with `curl`?
- for awk: line 308 of `ios_system.m`, it shoud be "libawk.dylib", not "libtext.dylib". I'm going to push a correction immediately.

**Comment by yury** [comment]
Hi @holzschu.
I'm back on utils. Today I started get error.

screen shot 2018-02-28 at 2 53 03 pm

**Comment by holzschu** [comment]
Hi @yury, 
I forgot to push half of the change. Try pulling `ios_system.m` now.

**Comment by yury** [comment]
hmmm, looking at get_frameworks.sh 
ios_system downloaded from releases.
and at the bottom it cloned.

**Comment by holzschu** [comment]
Terribly sorry, I also forgot to update the release. It should work now.

**Comment by yury** [comment]
No worries! I builded them from sources.

**Comment by yury** [comment]
@holzschu, here is my status update.

I'v implemented ctrl-c capture, but still can't figureout how to call ios_kill corretrly. I need ios_system to return me thread_id somehow. may be with callback.

awk works.
telnet - not :(

Still have ssh issue with keys. 
curl with https://ya.ru gives me:
```
curl: (77) SSL: can't load CA certificate file /var/mobile/Containers/Data/Application/937927A0-FCD9-4920-A57D-3E011591FE71/Documents/cacert.pem
```
I need to put somewhere cacert.pem?

Again, thanks for any help :)

**Comment by holzschu** [comment]
@yury, 

interactive telnet would be a long shot inside the current Blink architecture. Other shell commands assume no user interaction, making them easier. You will have the same issue with the interactive mode of nslookup (the non-interactive mode works fine). The problem is that the ios_system command is started as a joint thread, thus taking all resources, so there is no way to forward keyboard input to the command. One solution would be to start iOS_system in a separate thread, freeing the application to listen to commands. Another would be to restrict it to non-interactive commands. 

ios_kill() kills the current command running inside ios_system (and, by extension, all the commands it has started). It uses the variable `current_command_root_thread` and is basically equivalent to `if (current_command_root_thread > 0) pthread_cancel(current_command_root_thread);`. 

I realized you mean the ssh command inside ios_system. It was not designed to be used inside Blink, and so it does not use the Blink keys (I implemented it for iVim, to run "ls" on distant servers). My idea is that inside Blink, you would use the "ssh" already implemented. It's much better than mine, and interactive. It probably makes sense to remove libssh_cmd.dylib from the embedded frameworks. 

curl needs a cacert.pem, to be placed into ~/Documents/cacert.pem or in the position given by the environment variable SSL_CERT_FILE. You can take the one from your own computer or download one from https://curl.haxx.se/docs/caextract.html You'll probably want to include it in the official Blink distribution.

**Comment by holzschu** [comment]
@yury, 
Ctrl-C works well with an external keyboard, but not with the touchscreen keyboard. That's strange. 

Could you extend what you did so that any key typed on the keyboard (except Ctrl-C, of course) is sent to stdin? That would allow interactive commands like telnet and nslookup.

**Comment by yury** [comment]
@holzschu Sorry, not getting back to you sooner.

Ctrl-C - is kinda working, but if you open two tabs - iOS_kill kills random task.
I think, we need to split iOS_system or call back with thread_id, to send signal to thread.

About stdin - yep, I will do that. Next week is all about iOS_system!!!

**Comment by yury** [comment]
👋  @holzschu 

Updates from my side.

- Turn auto carriage return only for commands. Otherwise rendering in vim get broken
- Implemented Ctrl-C with software kb as well hybrid combos.
- Bundled cacert
- WIP on stdin
- Moved exec code to SystemSession.
- Grab cmd tid to kill it with ctrl-c

Please take a look at https://github.com/yury/ios_system/tree/blink  and https://github.com/yury/blink/tree/utils-threading

One interesting thing it seems that iOS_system are not thread save itself. 
Try to run `ping -c 1000 ya.ru` in one tab and `ping -c 1000 google.com` in other tab.
You would not see any output on google tab unless ya.ru finishes or get killed.

**Comment by holzschu** [comment]
@yury,
that looks awesome! I'll have a look. 

About iOS_system not being thread-save: you're absolutely right. It's a combination of me thinking it would not be possible and me thinking it would not be necessary. If you can make it so, that's really great. 

You can take a look at https://github.com/holzschu/ios_system/tree/experimental : it stores the list of commands in a plist file, for easier customisation on the App side. I'm not pushing it to the main branch so as not to confict with your work in progress.

**Comment by carloscabanero** [comment]
Hi @holzschu, just to clarify, does the app crash when accessing to the same file or even just to coordinateWritingItemAtURL accessing different ones?

**Comment by holzschu** [comment]
I'll have to reinstall the code and test again.

**Comment by holzschu** [comment]
Hi @yury, I've merged your thread-utils branch into https://github.com/holzschu/blink/tree/thread-utils using the experimental branch of ios_system for a thread-safe ios_system.

It seems to work, except for interactive commands.

**Comment by yury** [comment]
@holzschu looks great!!! 

Will merge with raw on Monday!!! And try interactive to work.

**Comment by yury** [comment]
Hi @holzschu.

Trying to build thread-utils with experimental branch. got it working, but have to delete libctags. and some commands (cat, ping) failed with `Symbol not found: _global_errno`

**Comment by yury** [comment]
@holzschu 

Merged thread-utils and blink/raw. You can check it here. https://github.com/yury/blink/tree/framework-utils

Mine todo:
- [ ] find a way to get and build all frameworks with script
- [ ] interactive commands (cat?)

**Comment by yury** [comment]
@holzschu testing all the things... Looks great!

One more question.

If I go out of sandboxed folder, I got `Operation not permitted` with `pwd` and it is ok. But `ls` crashes, because `currentPath` is `nil`.

img_0405

**Comment by holzschu** [comment]
Hi @yury, 
the last one was easy: I changed the order of operations, and check that `currentPath` exists before placing a lock on it:
```
                NSString* currentPath = [fileManager currentDirectoryPath];
                commandOperatesOnFiles &= (currentPath != nil);
                if (commandOperatesOnFiles) {
```
(commit 0fd694a) 
Also, if you don't want to allow the user to go outside the sandbox, you can use the function `ios_setMiniRoot`, which prevents `cd` from going outside of a certain directory (it could be `/private/var/mobile/Containers/Data/Application/.../Documents/`, for example).

**Comment by holzschu** [comment]
Hi @yury, 
I missed the question about `extraCommandsDictionary.plist`. If you don't want to use it, just set the variable `sideLoading` to false. 

`sideLoading` is supposed to be false for Apps to be submitted on the AppStore (less commands available, does not break the rules, exposes less informations about the internals), and true for users that compile and install on their own devices.

**Comment by holzschu** [comment]
Hi @yury, I've merged with your ongoing work. It looks good.
I would suggest calling `ios_setMiniRoot(docsPath)` in MCPSession.m, right after `initializeEnvironment()`: these are commands you only need to call once, to set things up.

**Comment by yury** [comment]
@holzschu thanks! moved to MCPSession.

In general, I think we are ok for first iteration. And we will make next TF with utils, I hope.

Huge thanks for such huge work you are doing.

**Comment by holzschu** [comment]
Hi @yury, just so you know, I have merged experimental with master in ios_system:
https://github.com/holzschu/ios_system
and released precompiled frameworks: 
https://github.com/holzschu/ios_system/releases/tag/v2.0

**Comment by yury** [comment]
@holzschu trying v2.0 but got no output...

**Comment by yury** [comment]
Pushed what I got to https://github.com/yury/blink/tree/rn

plists are bundled. And commands loaded. But output is blank..

**Comment by yury** [comment]
@holzschu If I build frameworks with xcodebuild - everything is ok.

**Comment by holzschu** [comment]
Oh, you mean the precompiled frameworks have an issue / incompatibility ?

**Comment by yury** [comment]
Yep, it is 100% reproducible. If I get frameworks with [script](https://github.com/yury/blink/blob/rn/get_frameworks.sh#L15)
commands have no output.

If I build frameworks and replace them - everything is ok.

**Comment by holzschu** [comment]
Hi @yury, I've edited the v2.0 release with a freshly re-compiled version of the frameworks. Does it work better with this one?

**Comment by yury** [comment]
Hi @holzschu, just tried again. Nope, same thing. I'm downloading https://github.com/holzschu/ios_system/releases/download/v2.0/release.tar.gz - right?

**Comment by yury** [comment]
```
~ ❯❯❯ curl -OL https://github.com/holzschu/ios_system/releases/download/v2.0/release.tar.gz                                                                                                                                                                              ⏎
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   605    0   605    0     0    911      0 --:--:-- --:--:-- --:--:--   912
100 35.5M  100 35.5M    0     0  1023k      0  0:00:35  0:00:35 --:--:-- 1735k
~ ❯❯❯ md5 release.tar.gz
MD5 (release.tar.gz) = 0b2444d7edb879a0e2a694a4b0938f4d
```

**Comment by yury** [comment]
Hi @holzschu 

Yep, you are right. touch do leave file it appears in files and cat <tab> completes it and history.txt.

**Comment by yury** [comment]
He he! Under debugger, I got output from commands to Xcode debugger :)

**Comment by yury** [comment]
@holzschu  how did you build frameworks?

**Comment by yury** [comment]
Hi @holzschu 
I don't have any idea too. If I cd to `../ios_system` and run `xcodebuild -project ios_system.xcodeproj -alltargets -sdk iphoneos -configuration Debug -quiet`, then copy frameworks to blink/Frameworks - everything is ok.

**Comment by holzschu** [comment]
Hi @yury, 
I was able to reproduce the issue, and found the solution. I've submitted as a PR on your branch. Let me know if it works.

**Comment by yury** [comment]
Thank you

**Comment by yury** [comment]
Hi @holzschu !

2 stupid questions :)

1. Why ctags is dylib and not framework? Should I build it build script?
2. How to set to false sideloading variable?

screen shot 2018-04-25 at 10 39 22 am

**Comment by holzschu** [comment]
Hi @yury, 

these are easy questions: 
- ctags is only useful inside an editor, such as iVim. It can safely be omited with terminals and shells like Blink. For now, the manager of iVim is not interested in ios_system for AppStore distribution, so I haven't made the library a framework.
- The variable name is "sideLoading", with a capital L.

**Comment by yury** [comment]
Hi @holzschu 

About ctags is in commandDictionary.plist not in extraCommandsDictionary.plist. Should I just remove it from commandDictionary.plist?

about sideLoading :) 

Still confused a little bit:

screen shot 2018-04-25 at 10 48 02 am

Should sideLoading also change completion list?
This way it kinda compiles, but i'm not sure it is changes anything.
screen shot 2018-04-25 at 10 50 56 am

**Comment by holzschu** [comment]
ctags can safely be moved to extraCommandsDictionary.plist; I did in recent versions of ios_system. 

ios_system/ios_system.h sould contain: "extern bool sideLoading;" (and it should be false by default, I'm going to re-release ios_system).

**Comment by yury** [comment]
Yep, it should change completion. But just can't set that global var properly

**Comment by holzschu** [comment]
Is "rn" still the branch you're using? I'll have a look.

**Comment by yury** [comment]
yep.

**Comment by holzschu** [comment]
I don't know why, but if you move the line inside the main() function, juste before the first call to iOS_system (line 303, before initializeEnvironment()), it works perfectly.

**Comment by yury** [comment]
@holzschu thanks!!!

Ok, I updated plists too. Now all seems perfect to me :)

**Comment by yury** [comment]
Hi @holzschu!

Testing utils. And stepped on interesting crash :)

After running `du /` or other command. Then try to run `mosh` - bam, crash.
Can't repeat this crash with ssh and mosh commands. Only after utils...

Any hint would help. No crash logs or stack traces :(

**Comment by holzschu** [comment]
Hi @yury, 
I can reproduce the crash. Like you, I have no idea what's happening, except that `setlocale()` returns "bad file descriptor". 

After that, it seems to go into iosclient.cc (line 87), but I don't have the source code for that one. It might help to have a version of `libmoshios` compiled with debugging information.

**Comment by holzschu** [comment]
Hi @yury, 
still no solutions. The `perror` function at line 109 of `locale_utils.cc` gets called. After that, the code enters `iosclient.cc`, and the crash happens in there. Calling `setlocale` inside `MCPSession.m` does not fail, which is odd.

**Comment by yury** [comment]
Hi @holzschu,

Another interesting observation. If on fresh start you run mosh first, exit session, run utils commands, and then mosh again - it is not crash.

**Comment by holzschu** [comment]
Hi @yury, 
the latest version of `ios_system` has wildcard expansion (`ls *.txt`, `rm *.log`). It is quite useful. You probably want that.

**Comment by yury** [comment]
Hi @holzschu,

Sure! that would be great. It will be v2.1 release? Or it is better to fork ios_system? What do you think?

**Comment by yury** [comment]
@holzschu, I also pass err stream to ios_system. That way `curl | grep` produce a little better output on the screen

**Comment by carloscabanero** [comment]
One more thing @holzschu, the last Blink version works with descriptors instead of streams, so we don't need to do fprintf all the time, etc... This may be useful and easier to port some of the tools and keep them in sync.

**Comment by holzschu** [comment]
I don't see the change to descriptors yet in the main branch. The switch from streams to descriptors will require some changes in ios_system and its API. With the current architecture, it should be relatively easy (but not instantaneous).

**Comment by carloscabanero** [comment]
Blink will continue to support both,. Just mentioned that in case it helps you with maintenance as usually this apps expect descriptors and not streams.

**Comment by yury** [comment]
Hi @holzschu,

We plan to migrate to new folders structure:

```
~/history.txt -> ~/.blink_history # or ~/.blink/history.txt
~/known_hosts -> ~/.ssh/known_hosts
~/defaults -> ~/.blink/defaults
~/hosts -> ~/.blink/hosts
~/keys -> ~/.blink/keys # or ~/.ssh/<keys>
```

Quick search showed that you do checks if files exists and fallback to known defaults in curl_ios_static/src/tool_operate.c

But maybe I missed something?

**Comment by holzschu** [comment]
Hi @yury,
Thanks for the heads up.
For `known_hosts`, yes, I search for it in `~/Documents/known_hosts ` and then in `~/Documents/.ssh/known_hosts`, so the change should not affect `ios_system`. 

I don't think I'm accessing the other ones.

**Comment by yury** [comment]
Ok, bad news...

Workaround on setlocale actually masks the problem. It doesn't crash, but mosh session resets its utf-8 locale somehow.

Scenario for replicating is more complex now.
1. first tab - mosh to server. Run `htop` or type any non ascii chars. - every thing is ok.
2. open second tab. Type `ls -la`.
3. switch to first tab. Run `htop` - will get bad screen. all non ascii chars will be replaced with `<?>` (On latest rn branch. On TF htop will behave strange)

**Comment by holzschu** [comment]
Hi @yury, 
I've been testing things .
`set locale(LC_ALL, "")` anywhere except in libmosh returns "C". Which is not the right answer (the terminal has UTF-8 abilities), but at least it doesn't crash. 
`set locale(LC_ALL, "")` inside libmosh returns NULL. The question is: why only inside libmosh? Is there anything different with the terminal?

According to the man page, `setlocale` tries to access `/usr/share/locale/locale/category` and `/usr/local/share/locale/locale/category`, which don't exist in iOS sandboxed environment. One possibility would be to define `$PATH_LOCALE` and provide locale descriptions in `$PATH_LOCALE/locale/category`.

**Comment by holzschu** [comment]
Hi @yury, 
I'm curious: what do you set `PATH_LOCALE` to?

**Comment by yury** [comment]
Hi @holzschu,

https://github.com/yury/blink/blob/rn/Blink/AppDelegate.m#L59

```obj-c
  NSString *locales_path = [mainBundle pathForResource:@"locales" ofType:@"bundle"];
  setenv("PATH_LOCALE", locales_path.UTF8String, forceOverwrite);
```

**Comment by yury** [comment]
yep, it is only LC_CTYPE in the bundle

**Comment by holzschu** [comment]
Hi @yury, 
OK, thanks. 
I got the latest version, plus a version of `ios_system` where `ls.c` calls `set locale()`. It seems to work (I don't see any differences on `ls -la`, for example). For more consistency, you could setenv `LC_CTYPE` to `UTF-8` in `AppDelegate.m`, so every command uses UTF-8.

**Comment by yury** [comment]
Hi @holzschu,

Here the [short video](https://m.youtube.com/watch?v=oT7es2XnJOo) what I get.

**Comment by holzschu** [comment]
Hi @yury, 
I'm going to install `htop` to reproduce. Right now, I have files named with emojis in the first terminal (running mosh) and `ls -la` in the second terminal.

**Comment by holzschu** [comment]
Quick question: does adding `setenv("LC_CTYPE", "UTF-8", 1);` on line 61 of `AppDelegate.m` change anything?

**Comment by yury** [comment]
actually not.

**Comment by yury** [comment]
oh, sorry!

It works!

**Comment by yury** [comment]
@holzschu thanks a lot! Testing...

**Comment by carloscabanero** [comment]
Alright, it has been quite a ride but we could finally put all the pieces together!!

Thanks a lot @holzschu for such a great work. We will continue contributing to tools on your repo 👍

**Comment by holzschu** [comment]
That is both awesome and overwhelming. It's awesome that you guys continue contributing to the tools!

**Pull request closed without merging**
