### PR TITLE
Basic QR scan functionality

### LINKED ISSUE #244: [Mahor] Can not import ssh keys
Hi,

just bought blink and installed it on iPhone 7+. I can not import my ssh keys which is a fail at the moment! Sorry, if I am annoyed, but if I just paid ~20€ than I expect that the basics do work

It does not accept my ed25519 nor my RSA4096 private keys. In both cases I get asked for the passphrase, I enter it and it asks me again and again until I abort.

I "cat" them on my terminal and copied them (on Mac), back on iOS I chose import from clipboard. I do not see any other way to get the keys onto my clipboard. Even writing the keys (not as attachment) via email and copying them on the iOS device, the app tells me the keys would be invalid.

Also, there is no option to send the keys via email and use "open in...", which would make things safer (I can S/MIME encrypt it to myself) and not using iCloud for clipboard.

So currently I can not do anything with this app :-(

### PR DESCRIPTION
**Pull request by hryamzik**
Added basic QR scan functionality. Works in the same way as clipboard pasting: only RSA keys are supported. Could help with #244 but also affected with it - invalid string leads to an infinite loop.

Didn't have a chance to test with pass-phrases.

QR code could be generated with

```
brew install qrencode
cat id_rsa|qrencode -t png -o rsa.png && open rsa.png
```

or if your screen is large enough

```
cat id_rsa|qrencode -t ANSI256
```

`ANSI256` works fine for `ed25519` on reasonably-sized screens but it's not supported yet.

### CODE REVIEW

**Comment by hryamzik** [comment]
@carloscabanero I could also fix infinite loop reported in #244 and add other key formats support, but starting this work from current master will make new PR conflict with this one.

**Comment by carloscabanero** [comment]
Thanks a lot @hryamzik!!! Will definitely push to the next version. If you can add other key formats support, hit me up on cc (at) blink.sh and we can arrange something. We are currently evaluating to move to either PuTTy or libssh too, specially for other keys support and more features.

**Comment by hryamzik** [comment]
Is there anything preventing merge? Did I select wrong branch?

**Comment by hryamzik** [comment]
Looks like ed25519 [isn't supported by libssh2 yet](https://github.com/libssh2/libssh2/issues/39), that's bad news.

**Comment by goerz** [comment]
It would be great if Blink could display its private keys as a QR code as well. I do like to use just one key for Blink on all of my different iOS devices. This way, I could generate a key on the iPad, display it as a QR code, and then simply import it to the iPhone by pointing the camera to the iPad screen. That seems more secure than having to email the key to myself, or anything like that.

**Comment by hryamzik** [comment]
I think private keys should be synced between devices with keychain, not QR codes.

**Review by loot-king — APPROVED** [review]
Update files

**Review by Dalvin12d — APPROVED** [review]

**Comment by hryamzik** [comment]
I don't have time to update this, feel free to push more changes here or to create a new PR.

**Comment by carloscabanero** [comment]
We did not do a good job at merging this and it has I think there are better ways at moving keys around now. Closing here.

**Pull request closed without merging**
